/* eslint-disable prettier/prettier */
/**
 * @Date: Sat Dec 11 2021 12:05:49 GMT+0530 (India Standard Time)
 * @Desc: Auto Generated - Plugin Based File Require
 */
 const FILEPATH = {
  Default: {
    Comments: require('../screens/Default/Comments/Index.tsx').default,
    Home: require('../screens/Default/Home/Index.tsx').default,
    LanguageSelection: require('../screens/Default/LanguageSelection/Index.tsx')
      .default,
    Benefits: require('../screens/Default/Benefits/Index.tsx')
      .default,
    SuccessMessage: require('../screens/Default/SuccessMessage/Index.tsx').default,
    CommunityFilter: require('../screens/Default/CommunityFilter/Index.tsx').default,
    MyBookmark: require('../screens/Default/MyBookmark/Index.tsx').default,
    VideoPlayer: require('../screens/Default/VideoPlayer/Index.tsx').default,
    Faq: require('../screens/Default/Faq/Index.tsx').default,
    ActivityCalendar: require('../screens/Default/ActivityCalendar/Index.tsx').default,
    ActivityShow: require('../screens/Default/ActivityShow/Index.tsx').default,
    AddActivity: require('../screens/Default/AddActivity/Index.tsx').default,
    Cart: require('../screens/Default/Cart/Index.tsx').default,
    Checkout: require('../screens/Default/Checkout/Index.tsx').default,
    ReviewOrder: require('../screens/Default/ReviewOrder/Index.tsx').default,
    SidebarSetting: require('../screens/Default/SidebarSetting/Index.tsx').default,
    ReceivedOrder: require('../screens/Default/ReceivedOrder/Index.tsx').default,
    Ecommerce: require('../screens/Default/Ecommerce/Index.tsx').default,
    EditProfile: require('../screens/Default/EditProfile/Index.tsx').default,
    ProductDetail: require('../screens/Default/ProductDetail/Index.tsx').default,
    WellnessCategory: require('../screens/Default/WellnessCategory/Index.tsx').default,
    WellnessCategoryItem: require('../screens/Default/WellnessCategoryItem/Index.tsx').default,
    Community: require('../screens/Default/Community/Index.tsx').default,
    CommunityComment: require('../screens/Default/CommunityComment/Index.tsx').default,
    FilterBlogDiscussion: require('../screens/Default/FilterBlogDiscussion/Index.tsx').default,
    FilterCommunity: require('../screens/Default/FilterCommunity/Index.tsx').default,
    ProfileMatch: require('../screens/Default/ProfileMatch/Index.tsx').default,
    Landing: require('../screens/Default/Landing/Index.tsx').default,
    Otp: require('../screens/Default/Otp/Index.tsx').default,
    Login: require('../screens/Default/Login/Index.tsx').default,
    Stories: require('../screens/Default/Stories/Index.tsx').default,
    ViewStory: require('../screens/Default/ViewStory/Index.tsx').default,
    UserOnBoarding: require('../screens/Default/UserOnBoarding/Index.tsx')
      .default,
    Payment: require('../screens/Default/Payment/Index.tsx').default,
    CreateDietPlan: require('../screens/Default/CreateDietPlan/Index.tsx')
      .default,
    DietPlan: require('../screens/Default/DietPlan/Index.tsx').default,
    AntiCancerDietPlan:
      require('../screens/Default/AntiCancerDietPlan/Index.tsx').default,
    NutrientInformation:
      require('../screens/Default/NutrientInformation/Index.tsx').default,
    FoodSearch: require('../screens/Default/FoodSearch/Index.tsx').default,
    UnlockNow: require('../screens/Default/UnlockNow/Index.tsx').default,
    ViewStory: require('../screens/Default/ViewStory/Index.tsx').default,
    MenuDetailScreen: require('../screens/Default/MenuDetailScreen').default,
    VideoScreen: require('../screens/Default/VideoScreen/Index.tsx').default,
    CreatePost: require('../screens/Default/CreatePost/Index.tsx').default,
    GroupDetail: require('../screens/Default/GrpupDetail/Index.tsx').default,
    ViewallGroup: require('../screens/Default/ViewallGroup/Index.tsx').default,
    ProfileScreen: require('../screens/Default/ProfileScreen/Index.tsx').default,
    Chat: require('../screens/Default/Chat/Index.tsx').default,
    Journal: require('../screens/Default/Journal/Index.tsx').default,
    JournalDetail: require('../screens/Default/JournalDetail/Index.tsx').default,
    ClinicalTrials: require('../screens/Default/ClinicalTrials/Index.tsx').default,
    ChatConversations: require('../screens/Default/ChatConversations/Index.tsx').default,
    ChatSearchPeople: require('../screens/Default/ChatSearchPeople/Index.tsx').default,
    Report: require('../screens/Default/Report/Index.tsx').default,
    AddMemory: require('../screens/Default/AddMemory/Index.tsx').default,
    AddReports: require('../screens/Default/AddReports/Index.tsx').default,
    ChatVideo: require('../screens/Default/ChatVideo/Index.tsx').default,
    ChatAudio: require('../screens/Default/ChatAudio/Index.tsx').default,
    ProfileMatchDetail: require('../screens/Default/ProfileMatchDetail/Index.tsx').default,
    Oncologist: require('../screens/Default/Oncologist/Index.tsx').default,
    OncologistBook: require('../screens/Default/OncologistBook/Index.tsx').default,
    LeaderBoard: require('../screens/Default/LeaderBoard/Index.tsx').default,
    AccountSetting: require('../screens/Default/AccountSetting/Index.tsx').default,
    Notification: require('../screens/Default/Notification/Index.tsx').default,
    Symptoms: require('../screens/Default/Symptoms/Index.tsx').default,
    ReportDetail: require('../screens/Default/ReportDetail/Index.tsx').default,
    Summary: require('../screens/Default/Summary/Index.tsx').default,
    NotificationList: require('../screens/Default/NotificationList/Index.tsx').default,
    HomeNotification: require('../screens/Default/HomeNotification/Index.tsx').default,
    OncologistBooked: require('../screens/Default/OncologistBooked/Index.tsx').default,
    ReviewList: require('../screens/Default/ReviewList/Index.tsx').default,
    Events: require('../screens/Default/Events/Index.tsx').default,
    EventFilter: require('../screens/Default/EventFilter/Index.tsx').default,
    EventsDetail: require('../screens/Default/EventsDetail/Index.tsx').default,
    MyOrders: require('../screens/Default/MyOrders/Index.tsx').default,
    MyOrderDetail: require('../screens/Default/MyOrderDetail/Index.tsx').default,
    FinancialResources: require('../screens/Default/FinancialResources/Index.tsx').default,
    FinancialResourcesDetail: require('../screens/Default/FinancialResourcesDetail/Index.tsx').default,
    ZenPoints: require('../screens/Default/ZenPoints/Index.tsx').default,
    ReferEarn: require('../screens/Default/ReferEarn/Index.tsx').default,
    AddEvent: require('../screens/Default/AddEvent/Index.tsx').default,
    Subscription: require('../screens/Default/Subscription/Index.tsx').default,
    SubscriptionDetail: require('../screens/Default/SubscriptionDetail/Index.tsx').default,
    News: require('../screens/Default/News/Index.tsx').default,
    NewsDetail: require('../screens/Default/NewsDetail/Index.tsx').default,
    VitalsMonitoring: require('../screens/Default/VitalsMonitoring/Index.tsx').default,
    VitalsDetail: require('../screens/Default/VitalsDetail/Index.tsx').default,
    EmergencyContacts: require('../screens/Default/EmergencyContacts/Index.tsx').default,
    Patients: require('../screens/Default/Patients/Index.tsx').default,
    DoctorsList: require('../screens/Default/DoctorsList/Index.tsx').default,
    TimeSlots: require('../screens/Default/TimeSlots/Index.tsx').default,
    DoctorDetails: require('../screens/Default/DoctorDetails/Index.tsx').default,
    MyAppointment: require('../screens/Default/MyAppointment/Index.tsx').default,
    WriteReview: require('../screens/Default/WriteReview/Index.tsx').default,
    PatientReviews: require('../screens/Default/PatientReviews/Index.tsx').default,
    VideoAppointment: require('../screens/Default/VideoAppointment/Index.tsx').default,
    AppointmentConfirm: require('../screens/Default/AppointmentConfirm/Index.tsx').default,
    AppointmentCancellation: require('../screens/Default/AppointmentCancellation/Index.tsx').default,
    AppointmentCancelled: require('../screens/Default/AppointmentCancelled/Index.tsx').default,
    CommunitySearch: require('../screens/Default/CommunitySearch/Index.tsx').default,
    Info: require('../screens/Default/Info/Index.tsx').default,
    Coupons: require('../screens/Default/Coupons/Index.tsx').default,
    Filters: require('../screens/Default/Filters/Index.tsx').default,
    WebScreen: require('../screens/Default/WebScreen/Index.tsx').default,
  },
};

export default FILEPATH;
