/* App config for theme */

const darKTheme = {
  theme_key: 'DARK_THEME',
  PRIMARY: '#FFFFFF',
  SECONDARY_WHITE: '#F9F9F9',
  SECONDARY: '#108FE5',
  TERTIARY: '#F9F6F6',
  LIGHT_BLUE: '#E9F3FF',
  LIGHT_GREEN: '#19CEAB',
  VERY_LIGHT_GRAY: "#EBEBEB",
  LIGHT_GRAY: '#CED3D9',
  MEDIUM_GRAY: '#8A9099',
  DARK_GRAY: '#5C6572',
  GHOST_WHITE: '#F1F4FF',
  BLACK: '#000000',
  RED: '#FC6262',
  GOLD: "#FEC132",
  GRAY_BLACK: "#333333",
  MINUTE_GRAY: "#8d8d8d",
  SECONDARY_OPACITY: "#F3F9FE",
  SUB_TITLE: "#666666",
  SEARCH_TITLE: "#999999",
  OTP_BORDER: "#c1c1c1",
  INPUT_BG: "#f0f5fe",
  HOME_HEADER: '#0052a8',
  FAQ_BG: '#f2f2f2',
  FAQ_ITEM_BG: '#fafafa',
  PAGINATION_DESELECT: '#79f8df',
  PAGINATION_SELECCT: '#108fe5',
  BG: '#f2f9fe',
  STROKE_COLOR: '#d7e1fb',
  ICON_TINT: '#19ceab',
  LIGHT_GREEN1: "#ddf8f2",
  RED_COLOR: "#ff4646",
  OFFER: "#ff0000",
  BORDER_COLOR: '#d5d5d5',
  SKY_BLUE: '#e2f1fc',
  SELECTED: '#f5f6fa',
  ACD_BG_COLOR: "aliceblue",
  LIGHT_SKY: '#b5fff1',
  LIGHT_SILVER: '#F3F4F9',
  SECONDARY_TWO: '#4fb4f8',
  TAB_BG: '#e4e6ea',
  SUB_TEXT: "#464646",
  DARK_SILVER: "#e4e5ea",
  SKY_BLUE_EVENT: '#e9f3ff',
  SEMI_GRAY: '#f5f5f5',
  SKY_GREEN: '#e3f5f9',
  BANNER_BG: '#389CDF',
  RED_TXT: '#e00027',
  HOME_BORDER: '#cccccc',
  BORDER_GREAY: '#D9D9D9',
  LIGHT_BORDER: '#EEEEEE',
  LIGHT_GREY: '#f3f3f3',
  SLOT_BORDER: '#CCCCCC',
  LIGHT_YELLOW: '#F8F9F2',
  LIGHT_YELLOW_BORDER: '#EEF1D5',
  GREEN: '#0C8A12',
  SECONDARY_BORDER: '#989898',
  LIGHT_BLUE_BORDER: '#E4E6EA',
  SECONDARY_RED: '#FF4040',
};

const lightTheme = {
  theme_key: 'LIGHT_THEME',
  PRIMARY: '#FFFFFF',
  SECONDARY_WHITE: '#F9F9F9',
  SECONDARY: '#108FE5',
  TERTIARY: '#F9F6F6',
  LIGHT_BLUE: ' #E9F3FF',
  LIGHT_GREEN: '#19CEAB',
  VERY_LIGHT_GRAY: "#EBEBEB",
  LIGHT_GRAY: '#CED3D9',
  MEDIUM_GRAY: '#8A9099',
  DARK_GRAY: '#5C6572',
  GHOST_WHITE: '#F1F4FF',
  BLACK: '#000000',
  RED: '#FC6262',
  GOLD: "#FEC132",
  GRAY_BLACK: "#333333",
  MINUTE_GRAY: "#8d8d8d",
  SECONDARY_OPACITY: "#F3F9FE",
  SUB_TITLE: "#666666",
  SEARCH_TITLE: "#999999",
  OTP_BORDER: "#c1c1c1",
  INPUT_BG: "#f0f5fe",
  HOME_HEADER: '#0052a8',
  FAQ_BG: '#f2f2f2',
  FAQ_ITEM_BG: '#fafafa',
  PAGINATION_DESELECT: '#79f8df',
  PAGINATION_SELECCT: '#108fe5',
  BG: '#f2f9fe',
  STROKE_COLOR: '#d7e1fb',
  ICON_TINT: '#19ceab',
  LIGHT_GREEN1: "#ddf8f2",
  RED_COLOR: "#ff4646",
  OFFER: "#ff0000",
  BORDER_COLOR: '#d5d5d5',
  SKY_BLUE: '#e2f1fc',
  SELECTED: '#f5f6fa',
  ACD_BG_COLOR: "aliceblue",
  LIGHT_SKY: '#b5fff1',
  LIGHT_SILVER: '#F3F4F9',
  SECONDARY_TWO: '#4fb4f8',
  TAB_BG: '#e4e6ea',
  SUB_TEXT: "#464646",
  DARK_SILVER: "#e4e5ea",
  SKY_BLUE_EVENT: '#e9f3ff',
  SEMI_GRAY: '#f5f5f5',
  SKY_GREEN: '#e3f5f9',
  HOME_BORDER: '#cccccc',
  BORDER_GREAY: '#707070',
  LIGHT_BORDER: '#EEEEEE',
  LIGHT_GREY: '#f3f3f3',
  SLOT_BORDER: '#CCCCCC',
  LIGHT_YELLOW: '#F8F9F2',
  LIGHT_YELLOW_BORDER: '#EEF1D5',
  SECONDARY_BORDER: '#989898',
  SECONDARY_RED: '#FF4040',
};

const rtlStyles = {
  alignItems: 'flex-start',
  textAlign: 'right',
  flexDirection: 'row-reverse',
  key: 'RTL',
  RTL: true,
};

const ltrStyles = {
  alignItems: 'flex-end',
  textAlign: 'left',
  flexDirection: 'row',
  key: 'LTR',
  RTL: false,
};

export const layoutStyles = [rtlStyles, ltrStyles];
const themes = [darKTheme, lightTheme];
export default themes;
