import actionTypes from '../actions/types';

import { all, takeEvery, takeLatest } from 'redux-saga/effects';
import { getRequest, postRequest, postFormDataRequest, putRequest } from '../../services/stories';
import {
  getAllStoriesSaga,
  getStoriesByUserIdSaga,
  addCommentsSaga,
  getCommentsByIdSaga,
  getStoriesByIdSaga,
  addSupportSaga,
  getDiscoverSaga,
  getRecentStoriesSaga,
  updateBookmarkSage,
  getMenuListDataSaga,
  getFaqListDataSaga,
  getCommunityListDataSaga,
  addSummarySaga,
  getCommunityGroupListDataSaga,
  getCommunityCategoryListDataSaga,
  getCommunityByIdListDataSaga,
  getCommunityDetailDataSaga,
  getCommunityGroupDetailDataSaga,
  joinGroupSaga,
  pinGroupSaga,
  getGroupMemberDataSaga,
  getGroupPostDataSaga,
  getRulesSaga,
  userReportSaga,
  myBookmarkSaga,
  blockUserSaga,
  reportOptionSaga,
} from './storiesSaga';
import {
  getReferralCodeSaga,
  getReferralCoinSaga,
  getNewsDetailSaga, getNewsListSaga, getNewsSearchSaga, getNewsBookMarktSaga
} from './referralSaga'
import {
  getDietPlanSaga,
  createDietPlanSaga,
  getCuisinesSaga,
  getDietPreferenceSaga,
  postAllergiesFoodsSaga,
  postCuisineFoodsSaga,
  postDietPreferenceSaga,
  getDietFoodInfoSaga,
  getSimilarFoodSaga,
  getFoodItemBfSaga,
  setTrackFoodSaga,
  changeRandomFoodSaga,
  getFoodItemLuSaga,
  getFoodItemSnSaga,
  searchFoodItemSaga,
  submitFoodItemSaga,
  checkFlowSaga,
  getAllergiesSaga,
} from './dietPlanSaga';
import {
  deactivateAccountSaga,
  deleteAccountSaga,
} from './settingSaga';
import {
    deleteActivitySaga
  } from './calendarSaga';
import { getAllHomeSaga } from './homeSaga';
import { addEventSaga, eventAllSaga, eventByCategorySaga, eventCategorySaga, eventLanguageSaga, financialResourceByIdSaga, financialResourcesSaga, registerEventSaga } from './eventSaga';
import { deleteEmergencyContactsSaga, fetchRpmSaga, getEmergencyContactsSaga, getRpmPermissionSaga, postEmergencyContactsSaga, postRpmPermissionSaga, postRpmSaga } from './rpmSaga';

export const saga2 = [
  takeEvery(actionTypes.GET_STORIES_ALL, getAllStoriesSaga, getRequest),
  takeEvery(actionTypes.GET_REFERRAL_CODE, getReferralCodeSaga, getRequest),
  takeEvery(actionTypes.GET_REFERRAL_COIN, getReferralCoinSaga, getRequest),
  takeEvery(actionTypes.GET_STORIES_BY_ID, getStoriesByIdSaga, getRequest),
  takeEvery(actionTypes.GET_STORIES_BY_USER_ID,getStoriesByUserIdSaga,getRequest,),
  takeEvery(actionTypes.ADD_COMMENTS, addCommentsSaga, postFormDataRequest),
  takeEvery(actionTypes.GET_COMMENTS_BY_ID, getCommentsByIdSaga, getRequest),
  takeEvery(actionTypes.ADD_SUPPORT, addSupportSaga, postRequest),
  takeEvery(actionTypes.USER_REPORT, userReportSaga, postRequest),
  takeEvery(actionTypes.UPDATE_BOOKMARK, updateBookmarkSage, postRequest),
  takeEvery(actionTypes.GET_DISCOVER, getDiscoverSaga, getRequest),
  takeEvery(actionTypes.GET_RECENT_STORIES, getRecentStoriesSaga, getRequest),
  takeEvery(actionTypes.GET_CUISINES, getCuisinesSaga, getRequest),
  takeEvery(actionTypes.POST_CUISINE_FOODS,postCuisineFoodsSaga, postRequest,),
  takeEvery(actionTypes.GET_DIET_PREFERENCE,getDietPreferenceSaga,getRequest,),
  takeEvery(actionTypes.POST_DIET_PREFERENCE,postDietPreferenceSaga,postRequest,),
  takeEvery(actionTypes.POST_ALLERGIES_FOODS,postAllergiesFoodsSaga,postRequest,),
  takeEvery(actionTypes.CREATE_DIET_PLAN, createDietPlanSaga, postRequest),
  takeEvery(actionTypes.GET_DIET_PLAN, getDietPlanSaga, postRequest),
  takeEvery(actionTypes.GET_DIET_FOOD_INFO, getDietFoodInfoSaga, getRequest),
  takeEvery(actionTypes.GET_SIMILAR_FOODS, getSimilarFoodSaga, getRequest),
  takeEvery(actionTypes.GET_FOOD_ITEM_BF, getFoodItemBfSaga, getRequest),
  takeEvery(actionTypes.GET_FOOD_ITEM_LU, getFoodItemLuSaga, getRequest),
  takeEvery(actionTypes.GET_FOOD_ITEM_SN, getFoodItemSnSaga, getRequest),
  takeEvery(actionTypes.SEARCH_FOOD_ITEM, searchFoodItemSaga, getRequest),
  takeEvery(actionTypes.SUBMIT_FOOD_ITEM, submitFoodItemSaga, postRequest),
  takeEvery(actionTypes.CHECK_FLOW_DIET_PLAN, checkFlowSaga, getRequest),
  takeEvery(actionTypes.SET_TRACK_FOOD, setTrackFoodSaga, postRequest),
  takeEvery(actionTypes.CHANGE_RANDOM_FOOD,changeRandomFoodSaga,postRequest,),
  takeLatest(actionTypes.GET_MENU_LIST, getMenuListDataSaga, getRequest),
  takeLatest(actionTypes.GET_FAQ_LIST_DATA, getFaqListDataSaga, getRequest),
  takeLatest(actionTypes.GET_COMMUNITY_LIST_DATA, getCommunityListDataSaga, getRequest),
  takeLatest(actionTypes.DEACTIVATE_ACCOUNT, deactivateAccountSaga, postRequest),
  takeLatest(actionTypes.DELETE_ACCOUNT, deleteAccountSaga, postRequest),
  takeLatest(actionTypes.SUMMARY, addSummarySaga, putRequest),
  takeLatest(actionTypes.DELETE_ACTIVITY, deleteActivitySaga, putRequest),
  takeLatest(actionTypes.GET_COMMUNITY_GROUP_LIST_DATA, getCommunityGroupListDataSaga, getRequest),
  takeLatest(actionTypes.ALL_HOME, getAllHomeSaga, getRequest),
  takeLatest(actionTypes.REGISTER_EVENT, registerEventSaga, postRequest),
  takeLatest(actionTypes.GET_EVENT_CATEGORY, eventCategorySaga, getRequest),
  takeLatest(actionTypes.GET_EVENT_LANGUAGE, eventLanguageSaga, getRequest),
  takeLatest(actionTypes.GET_ALL_EVENTS, eventAllSaga, postRequest),
  takeLatest(actionTypes.ADD_EVENT, addEventSaga, postFormDataRequest),
  takeLatest(actionTypes.GET_CATEGORY_EVENTS, eventByCategorySaga, postRequest),
  takeLatest(actionTypes.GET_FINACIAL_RESOURCE, financialResourcesSaga, getRequest),
  takeLatest(actionTypes.MY_BOOKMARK, myBookmarkSaga, getRequest),
  takeLatest(actionTypes.GET_FINACIAL_RESOURCE_BY_ID, financialResourceByIdSaga, getRequest),
  takeLatest(actionTypes.GET_COMMUNITY_CATEGORY_LIST_DATA, getCommunityCategoryListDataSaga, getRequest),
  takeLatest(actionTypes.GET_COMMUNITY_BYID_LIST_DATA, getCommunityByIdListDataSaga, getRequest),
  takeLatest(actionTypes.RULES_ALL, getRulesSaga, getRequest),
  takeLatest(actionTypes.GET_COMMUNITY_DETAIL_DATA, getCommunityDetailDataSaga, getRequest),
  takeLatest(actionTypes.GET_GROUP_DETAIL_DATA, getCommunityGroupDetailDataSaga, getRequest),
  takeLatest(actionTypes.POST_JOIN_GROUP, joinGroupSaga, postRequest),
  takeLatest(actionTypes.POST_PIN_GROUP, pinGroupSaga, postRequest),
  takeLatest(actionTypes.GET_GROUP_MEMBERS_DATA, getGroupMemberDataSaga, getRequest),
  takeLatest(actionTypes.GET_GROUP_POSTS_DATA, getGroupPostDataSaga, getRequest),
  takeLatest(actionTypes.NEWS_LIST, getNewsListSaga, getRequest),
  takeLatest(actionTypes.NEWS_DETAIL, getNewsDetailSaga, getRequest),
  takeLatest(actionTypes.NEWS_SEARCH, getNewsSearchSaga, postRequest),
  takeLatest(actionTypes.RPM_GET_PERMISSION, getRpmPermissionSaga, getRequest),
  takeLatest(actionTypes.RPM_POST_PERMISSION, postRpmPermissionSaga, postRequest),
  takeLatest(actionTypes.CREATE_SOS, postEmergencyContactsSaga, postRequest),
  takeLatest(actionTypes.DELTE_SOS, deleteEmergencyContactsSaga, putRequest),
  takeLatest(actionTypes.FETCH_SOS, getEmergencyContactsSaga, getRequest),
  takeLatest(actionTypes.GET_ALLERGIES_FOODS, getAllergiesSaga, getRequest),
  takeLatest(actionTypes.FETCH_RPM, fetchRpmSaga, getRequest),
  takeLatest(actionTypes.POST_RPM, postRpmSaga, postRequest),
  takeLatest(actionTypes.BLOCK_USER, blockUserSaga, postRequest),
  takeLatest(actionTypes.REPORT_OPTIONS, reportOptionSaga, getRequest),
  takeLatest(actionTypes.GET_NEWS_BOOKMARK, getNewsBookMarktSaga, postRequest),
]
