const actionTypes: { [k: string]: string } = {
  NEW_LOADER: 'NEW_LOADER',
  LOADER: 'LOADER',
  UPDATE_APP_ACTION: 'EO_UPDATE_APP_ACTION',
  UPDATE_INTERNET_STATUS: 'EO_UPDATE_INTERNET_STATUS',
  UPDATE_BENIFIT: 'UPDATE_BENEFIT_DATA',
  BENIFIT_OBJECT: 'BENIFIT_OBJECT',
  CALL_OTP: 'CALL_OTP',
  OTP_DATA: 'OTP_DATA',
  V_USER: 'VERIFY_USER',
  USER_DATA: 'USER_DATA',
  INTERNET: 'INTERNET',
  LOGIN_STATUS: 'LOGIN_STATUS',

  CANCER_SEARCH_ALL: 'CANCER_SEARCH_ALL',
  CANCER_SEARCH_ALL_DATA: 'CANCER_SEARCH_ALL_DATA',
  CANCER_SEARCH: 'CANCER_SEARCH',
  CANCER_SEARCH_DATA: 'CANCER_SEARCH_DATA',

  CITY_SEARCH_ALL: 'CITY_SEARCH_ALL',
  CITY_SEARCH_ALL_DATA: 'CITY_SEARCH_ALL_DATA',
  CITY_SEARCH: 'CITY_SEARCH',
  CITY_SEARCH_DATA: 'CITY_SEARCH_DATA',

  MED_TREATMENT_ALL: 'MED_TREATMENT_ALL',
  MED_TREATMENT_ALL_DATA: 'MED_TREATMENT_ALL_DATA',

  USER_REPORT: 'USER_REPORT',
  USER_REPORT_DATA: 'USER_REPORT_DATA',

  ALL_HOME: 'ALL_HOME',
  ALL_HOME_DATA: 'ALL_HOME_DATA',

  SUMMARY: 'SUMMARY',
  SUMMARY_DATA: 'SUMMARY_DATA',

  CREATE_POST: 'CREATE_POST',
  CREATE_POST_DATA: 'CREATE_POST_DATA',

  ADD_EVENT: 'ADD_EVENT',
  ADD_EVENT_DATA: 'ADD_EVENT_DATA',

  GET_REFERRAL_CODE: 'GET_REFERRAL_CODE',
  GET_REFERRAL_CODE_DATA: 'GET_REFERRAL_CODE_DATA',

  GET_REFERRAL_COIN: 'GET_REFERRAL_COIN',
  GET_REFERRAL_COIN_DATA: 'GET_REFERRAL_COIN_DATA',

  CAM_TREATMENT_ALL: 'CAM_TREATMENT_ALL',
  CAM_TREATMENT_ALL_DATA: 'CAM_TREATMENT_ALL_DATA',

  HEALTH_STATUS_ALL: 'HEALTH_STATUS_ALL',
  HEALTH_STATUS_ALL_DATA: 'HEALTH_STATUS_ALL_DATA',

  RULES_ALL: 'RULES_ALL',
  RULES_ALL_DATA: 'RULES_ALL_DATA',

  GET_SURGERY: 'GET_SURGERY',
  GET_SURGERY_DATA: 'GET_SURGERY_DATA',

  GET_TREATMENT: 'GET_TREATMENT',
  GET_TREATMENT_DATA: 'GET_TREATMENT_DATA',

  ADD_USER_DETAILS: 'ADD_USER_DETAILS',
  ADD_USER_DETAILS_DATA: 'ADD_USER_DETAILS_DATA',

  EDIT_USER_DETAILS: 'EDIT_USER_DETAILS',
  EDIT_USER_DETAILS_DATA: 'EDIT_USER_DETAILS_DATA',

  GET_ALL_USERPROFILE: 'GET_ALL_USERPROFILE',
  GET_ALL_USERPROFILE_DATA: 'GET_ALL_USERPROFILE_DATA',

  GET_ALL_WELLNESS_CATEGORY: "GET_ALL_WELLNESS_CATEGORY",
  GET_ALL_WELLNESS_CATEGORY_DATA: "GET_ALL_WELLNESS_CATEGORY_DATA",

  GET_ALL_WELLNESS_CATEGORY_BYID: "GET_ALL_WELLNESS_CATEGORY_BYID",
  GET_ALL_WELLNESS_CATEGORY_BYID_DATA: "GET_ALL_WELLNESS_CATEGORY_BYID_DATA",

  GET_CANCER_STAGE: 'GET_CANCER_STAGE',
  GET_CANCER_STAGE_DATA: 'GET_CANCER_STAGE_DATA',

  GET_COUNTRY: 'GET_COUNTRY',
  GET_COUNTRY_DATA: 'GET_COUNTRY_DATA',

  GET_STATE: 'GET_STATE',
  GET_STATE_DATA: 'GET_STATE_DATA',

  GET_CUISINE: 'GET_CUISINE',
  GET_CUISINE_DATA: 'GET_CUISINE_DATA',

  GET_PHYSICAL_ACTIVITY: 'GET_PHYSICAL_ACTIVITY',
  GET_PHYSICAL_ACTIVITY_DATA: 'GET_PHYSICAL_ACTIVITY_DATA',

  GET_SYMPTOMS: 'GET_SYMPTOMS',
  GET_SYMPTOMS_DATA: 'GET_SYMPTOMS_DATA',

  GET_FACTORS: 'GET_FACTORS',
  GET_FACTORS_DATA: 'GET_FACTORS_DATA',

  GET_MEDICATIONS: 'GET_MEDICATIONS',
  GET_MEDICATIONS_DATA: 'GET_MEDICATIONS_DATA',

  GET_MEDICAL_ISSUES: 'GET_MEDICAL_ISSUES',
  GET_MEDICAL_ISSUES_DATA: 'GET_MEDICAL_ISSUES_DATA',

  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_DATA: 'GET_PAYMENT_DATA',

  GET_PAYMENT_PLANS: 'GET_PAYMENT_PLANS',
  GET_PAYMENT_PLANS_DATA: 'GET_PAYMENT_PLANS_DATA',

  GET_PAYMENT_VERFIY: 'GET_PAYMENT_VERIFY',
  GET_PAYMENT_VERIFY_DATA: 'GET_PAYMENT_VERIFY_DATA',

  FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
  FETCH_USER_DETAILS_DATA: 'FETCH_USER_DETAILS_DATA',

  FETCH_OTHER_DETAILS: 'FETCH_OTHER_DETAILS',
  FETCH_OTHER_DETAIL_DATA: 'FETCH_OTHER_DETAIL_DATA',

  GET_STORIES_ALL: 'GET_STORIES_ALL',
  GET_STORIES_ALL_DATA: 'GET_STORIES_ALL_DATA',

  GET_STORIES_BY_ID: 'GET_STORIES_BY_ID',
  GET_STORIES_BY_ID_DATA: 'GET_STORIES_BY_ID_DATA',

  GET_STORIES_BY_USER_ID: 'GET_STORIES_BY_USER_ID',
  GET_STORIES_BY_USER_ID_DATA: 'GET_STORIED_BY_USER_ID',

  ADD_COMMENTS: 'ADD_COMMENTS',
  ADD_COMMENTS_DATA: 'ADD_COMMENTS_DATA',

  GET_COMMENTS_BY_ID: 'GET_COMMENTS_BY_ID',
  GET_COMMENTS_BY_ID_DATA: 'GET_COMMENTS_BY_ID_DATA',

  ADD_SUPPORT: 'ADD_SUPPORT',
  ADD_SUPPORT_DATA: 'ADD_SUPPORT_DATA',

  UPDATE_BOOKMARK: 'UPDATE_BOOKMARK',
  UPDATE_BOOKMARK_DATA: 'UPDATE_BOOKMARK_DATA',

  GET_DISCOVER: 'GET_DISCOVER',
  GET_DISCOVER_DATA: 'GET_DISCOVER_DATA',

  GET_RECENT_STORIES: 'GET_RECENT_STORIES',
  GET_RECENT_STORIES_DATA: 'GET_RECENT_STORIES_DATA',

  GET_CUISINES: 'GET_CUISINES',
  GET_CUISINES_DATA: 'GET_CUISINES_DATA',

  GET_DIET_PREFERENCE: 'GET_DIET_PREFERENCE',
  GET_DIET_PREFERENCE_DATA: 'GET_DIET_PREFERENCE_DATA',

  GET_ALLERGIES_FOODS: 'GET_ALLERGIES_FOODS',
  GET_ALLERGIES_FOODS_DATA: 'GET_ALLERGIES_FOODS_DATA',

  POST_DIET_PREFERENCE: 'POST_DIET_PREFERENCE',
  POST_DIET_PREFERENCE_DATA: 'POST_DIET_PREFERENCE_DATA',

  POST_CATEGORY: 'POST_CATEGORY',
  POST_CATEGORY_DATA: 'POST_CATEGORY_DATA',

  POST_CUISINE_FOODS: 'POST_CUISINE_FOODS',
  POST_CUISINE_FOODS_DATA: 'POST_CUISINE_FOODS_DATA',

  POST_ALLERGIES_FOODS: 'POST_ALLERGIES_FOODS',
  POST_ALLERGIES_FOODS_DATA: 'POST_ALLERGIES_FOODS_DATA',

  CREATE_DIET_PLAN: 'CREATE_DIET_PLAN',
  CREATE_DIET_PLAN_DATA: 'CREATE_DIET_PLAN_DATA',

  GET_DIET_PLAN: 'GET_DIET_PLAN',
  GET_DIET_PLAN_DATA: 'GET_DIET_PLAN_DATA',

  GET_DIET_FOOD_INFO: 'GET_DIET_FOOD_INFO',
  GET_DIET_FOOD_INFO_DATA: 'GET_DIET_FOOD_INFO_DATA',

  GET_SIMILAR_FOODS: 'GET_SIMILAR_FOODS',
  GET_SIMILAR_FOODS_DATA: 'GET_SIMILAR_FOODS_DATA',
  GET_FOOD_ITEM_BF: 'GET_FOOD_ITEM_BF',
  GET_FOOD_ITEM_LU: 'GET_FOOD_ITEM_LU',
  GET_FOOD_ITEM_SN: 'GET_FOOD_ITEM_SN',

  GET_FOOD_ITEM_DATA_BF: 'GET_FOOD_ITEM_DATA_BF',
  GET_FOOD_ITEM_DATA_LU: 'GET_FOOD_ITEM_DATA_LU',
  GET_FOOD_ITEM_DATA_SN: 'GET_FOOD_ITEM_DATA_SN',

  SEARCH_FOOD_ITEM: 'SEARCH_FOOD_ITEM',
  SEARCH_FOOD_ITEM_DATA: 'SEARCH_FOOD_ITEM_DATA',

  SUBMIT_FOOD_ITEM: 'SUBMITE_FOOD_ITEM',
  SUBMIT_FOOD_ITEM_DATA: 'SUBIT_FOOD_ITEM_DATA',

  CHECK_FLOW_DIET_PLAN: 'CHECK_FLOW_DIET_PLAN',
  CHECK_FLOW_DIET_PLAN_DATA: 'CHECK_FLOW_DIET_PLAN_DATA',

  SET_TRACK_FOOD: 'SET_TRACK_FOOD',
  SET_TRACK_FOOD_DATA: 'SET_TRACK_FOOD_DATA',

  CHANGE_RANDOM_FOOD: 'CHANGE_RANDOM_FOOD',
  CHANGE_RANDOM_FOOD_DATA: 'CHANGE_RANDOM_FOOD_DATA',

  GET_MENU_LIST: 'GET_MENU_LIST',
  GET_MENU_LIST_DATA: 'GET_MENU_LIST_DATA',

  GET_DETAIL_MENU_ITEM: 'GET_DETAIL_MENU_ITEM',
  GET_DETAIL_MENU_ITEM_DATA: 'GET_DETAIL_MENU_ITEM_DATA',

  GET_FAQ_LIST_DATA: 'GET_FAQ_LIST_DATA',
  GET_FAQ_LIST_DATA_ALL: 'GET_FAQ_LIST_DATA_ALL',

  GET_COMMUNITY_LIST_DATA: 'GET_COMMUNITY_LIST_DATA',
  GET_COMMUNITY_LIST_DATA_ALL: 'GET_COMMUNITY_LIST_DATA_ALL',

  GET_COMMUNITY_BYID_LIST_DATA: 'GET_COMMUNITY_BYID_LIST_DATA',
  GET_COMMUNITY_BYID_LIST_DATA_ALL: 'GET_COMMUNITY_BYID_LIST_DATA_ALL',

  GET_COMMUNITY_GROUP_LIST_DATA: 'GET_COMMUNITY_GROUP_LIST_DATA',
  GET_COMMUNITY_GROUP_LIST_DATA_ALL: 'GET_COMMUNITY_GROUP_LIST_DATA_ALL',

  GET_COMMUNITY_CATEGORY_LIST_DATA: 'GET_COMMUNITY_CATEGORY_LIST_DATA',
  GET_COMMUNITY_CATEGORY_LIST_DATA_ALL: 'GET_COMMUNITY_CATEGORY_LIST_DATA_ALL',

  GET_COMMUNITY_DETAIL_DATA: 'GET_COMMUNITY_DETAIL_DATA',
  GET_COMMUNITY_DETAIL_DATA_ALL: 'GET_COMMUNITY_DETAIL_DATA_ALL',

  GET_GROUP_DETAIL_DATA: 'GET_GROUP_DETAIL_DATA',
  GET_GROUP_DETAIL_DATA_ALL: 'GET_GROUP_DETAIL_DATA_ALL',

  POST_JOIN_GROUP: 'POST_JOIN_GROUP',
  POST_JOIN_GROUP_ALL: 'POST_JOIN_GROUP_ALL',

  POST_PIN_GROUP: 'POST_PIN_GROUP',
  POST_PIN_GROUP_DATA_ALL: 'POST_PIN_GROUP_DATA_ALL',

  POST_PIN_STORY: 'POST_PIN_STORY',
  POST_PIN_STORY_DATA_ALL: 'POST_PIN_STORY_DATA_ALL',

  POST_FOLLOWLIST_STORY: 'POST_FOLLOWLIST_STORY',
  POST_FOLLOWLIST_DATA_ALL: 'POST_FOLLOWLIST_DATA_ALL',

  POST_REPORT_LIST_STORY: 'POST_REPORT_LIST_STORY',
  POST_REPORT_LIST_DATA_ALL: 'POST_REPORT_LIST_DATA_ALL',

  POST_MARK_AS_SPAM_STORY: 'POST_MARK_AS_SPAM_LIST_STORY',
  POST_MARK_AS_SPAM_DATA_ALL: 'POST_MARK_AS_SPAM_DATA_ALL',

  GET_GROUP_MEMBERS_DATA: 'GET_GROUP_MEMBERS_DATA',
  GET_GROUP_MEMBERS_DATA_ALL: 'GET_GROUP_MEMBERS_DATA_ALL',

  GET_GROUP_POSTS_DATA: 'GET_GROUP_POSTS_DATA',
  GET_GROUP_POSTS_DATA_ALL: 'GET_GROUP_POSTS_DATA_ALL',

  FITER_DATA: 'FITER_DATA',
  FITER_DATA_ALL: 'FITER_DATA_ALL',

  PROFILE_POST: 'PROFILE_POST',
  PROFILE_POST_ALL: 'PROFILE_POST_ALL',

  LIKE_FOOD: 'LIKE_FOOD',
  LIKE_FOOD_ALL: 'LIKE_FOOD_ALL',

  INGREDIENTS: 'INGREDIENTS',
  INGREDIENTS_ALL: 'INGREDIENTS_ALL',

  PRODUCT_CATEGORY: 'PRODUCT_CATEGORY',
  PRODUCT_CATEGORY_ALL: 'PRODUCT_CATEGORY_ALL',

  PRODUCT: 'PRODUCT',
  PRODUCT_ALL: 'PRODUCT_ALL',

  CATEGORY_PRODUCT: 'CATEGORY_PRODUCT',
  CATEGORY_PRODUCT_ALL: 'CATEGORY_PRODUCT_ALL',

  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  PRODUCT_DETAIL_ALL: 'PRODUCT_DETAIL_ALL',

  TAG_DATA: 'TAG_DATA',
  TAG_DATA_ALL: 'TAG_DATA_ALL',

  ADD_CART: 'ADD_CART',

  FOLLOW_USER: 'FOLLOW_USER',
  FOLLOW_USER_DATA: 'FOLLOW_USER_DATA',

  CREATE_ORDER: 'CREATE_ORDER',
  CREATE_ORDER_DATA: 'CREATE_ORDER_DATA',

  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  CREATE_CUSTOMER_DATA: 'CREATE_CUSTOMER_DATA',

  CREATE_CUSTOMER_SERVER: 'CREATE_CUSTOMER_SERVER',
  CREATE_CUSTOMER_SERVER_DATA: 'CREATE_CUSTOMER_SERVER_DATA',

  FETCH_CUSTOMER: 'FETCH_CUSTOMER',
  FETCH_CUSTOMER_DATA: 'FETCH_CUSTOMER_DATA',

  EDIT_CUSTOMER: 'EDIT_CUSTOMER',
  EDIT_CUSTOMER_DATA: 'EDIT_CUSTOMER_DATA',

  CREATE_ORDER_SERVER: 'CREATE_ORDER_SERVER',
  CREATE_ORDER_SERVER_DATA: 'CREATE_ORDER_SERVER_DATA',

  PRODUCT_IMAGES: 'PRODUCT_IMAGES',
  PRODUCT_IMAGES_DATA: 'PRODUCT_IMAGES_DATA',

  CREATE_CART: 'CREATE_CART',
  CREATE_CART_DATA: 'CREATE_CART_DATA',

  REFERRAL_CODE: 'REFERRAL_CODE',
  REFERRAL_CODE_DATA: 'REFERRAL_CODE_DATA',

  GET_CART: 'GET_CART',
  GET_CART_DATA: 'GET_CART_DATA',

  GET_JOURNAL_LIST: 'GET_JOURNAL_LIST',
  GET_JOURNAL_LIST_DATA: 'GET_JOURNAL_LIST_DATA',

  GET_JOURNAL_ITEM: 'GET_JOURNAL_ITEM',
  GET_JOURNAL_ITEM_DATA: 'GET_JOURNAL_ITEM_DATA',

  GET_JOURNAL_CATEGORY_LIST: 'GET_JOURNAL_CATEGORY_LIST',
  GET_JOURNAL_CATEGORY_LIST_DATA: 'GET_JOURNAL_CATEGORY_LIST_DATA',

  GET_JOURNAL_SEARCH_LIST: 'GET_JOURNAL_SEARCH_LIST',
  GET_JOURNAL_SEARCH_LIST_DATA: 'GET_JOURNAL_SEARCH_LIST_DATA',

  UPDATE_CART: 'UPDATE_CART',
  UPDATE_CART_DATA: 'UPDATE_CART_DATA',

  DELETE_CART: 'DELETE_CART',
  DELETE_CART_DATA: 'DELETE_CART_DATA',

  GET_ADDRESS: 'GET_ADDRESS',
  GET_ADDRESS_DATA: 'GET_ADDRESS_DATA',

  CREATE_ADDRESS: 'CREATE_ADDRESS',
  CREATE_ADDRESS_DATA: 'CREATE_ADDRESS_DATA',

  GET_CALENDAR: 'GET_CALENDAR',
  GET_CALENDAR_DATA: 'GET_CALENDAR_DATA',

  GET_PATIENT_DETAIL: 'GET_PATIENT_DETAIL',
  GET_PATIENT_DETAIL_DATA: 'GET_PATIENT_DETAIL_DATA',

  GET_CALENDAR_SUGGESTION: 'GET_CALENDAR_SUGGESTION',
  GET_CALENDAR_SUGGESTION_DATA: 'GET_CALENDAR_SUGGESTION_DATA',

  ADD_CALENDAR: 'ADD_CALENDAR',
  ADD_CALENDAR_DATA: 'ADD_CALENDAR_DATA',

  LEAVE_GROUP: 'LEAVE_GROUP',
  LEAVE_GROUP_DATA: 'LEAVE_GROUP_DATA',

  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_COMMENT_DATA: 'DELETE_COMMENT_DATA',

  EDIT_COMMENT: 'EDIT_COMMENT',
  EDIT_COMMENT_DATA: 'EDIT_COMMENT_DATA',

  CLEAR_CART: 'CLEAR_CART',
  CLEAR_CART_DATA: 'CLEAR_CART_DATA',

  GET_CONDITION: 'GET_CONDITION',
  GET_CONDITION_DATA: 'GET_CONDITION_DATA',

  EDIT_IMAGE: 'EDIT_IMAGE',
  EDIT_IMAGE_DATA: 'EDIT_IMAGE_DATA',

  GET_CHAT_CONVERSATION: 'GET_CHAT_CONVERSATION',
  GET_CHAT_CONVERSATION_DATA: 'GET_CHAT_CONVERSATION_DATA',

  GET_MY_REPORTS_LIST: 'GET_MY_REPORTS_LIST',
  GET_MY_REPORTS_LIST_DATA: 'GET_MY_REPORTS_LIST_DATA',

  GROUP_SEARCH: 'GROUP_SEARCH',
  GROUP_SEARCH_DATA: 'GROUP_SEARCH_DATA',

  CALENDAR_CATEGORY: 'CALENDAR_CATEGORY',
  CALENDAR_CATEGORY_DATA: 'CALENDAR_CATEGORY_DATA',

  ALL_WELLNESS: 'ALL_WELLNESS',
  ALL_WELLNESS_DATA: 'ALL_WELLNESS_DATA',

  GET_ONCOLOGIST_LIST: 'GET_ONCOLOGIST_LIST',
  GET_ONCOLOGIST_LIST_DATA: 'GET_ONCOLOGIST_LIST_DATA',

  GET_ONCOLOGIST_FILTER_LIST: 'GET_ONCOLOGIST_FILTER_LIST',
  GET_ONCOLOGIST_FILTER_DATA: 'GET_ONCOLOGIST_FILTER_DATA',

  EDIT_CALENDAR: 'EDIT_CALENDAR',
  EDIT_CALENDAR_DATA: 'EDIT_CALENDAR_DATA',

  CREATE_STREAK: 'CREATE_STREAK',
  CREATE_STREAK_DATA: 'CREATE_STREAK_DATA',

  GET_ONCOLOGIST_DR: 'GET_ONCOLOGIST_DR',
  GET_ONCOLOGIST_DR_DATA: 'GET_ONCOLOGIST_DR_DATA',

  GET_REPORTS_CATEGORY_LIST: 'GET_REPORTS_CATEGORY_LIST',
  GET_REPORTS_CATEGORY_LIST_DATA: 'GET_REPORTS_CATEGORY_LIST_DATA',

  GET_SPECIALIZATION_LIST: 'GET_SPECIALIZATION_LIST',
  GET_SPECIALIZATION_LIST_DATA: 'GET_SPECIALIZATION_LIST_DATA',

  GET_REPORTS_FILTER_LIST: 'GET_REPORTS_FILTER_LIST',
  GET_REPORTS_FILTER_LIST_DATA: 'GET_REPORTS_FILTER_LIST_DATA',

  GET_LEADERBOARD_LIST: 'GET_LEADERBOARD_LIST',
  GET_LEADERBOARD_LIST_DATA: 'GET_LEADERBOARD_LIST_DATA',

  GET_SYMPTOMS_LIST: 'GET_SYMPTOMS_LIST',
  GET_SYMPTOMS_LIST_DATA: 'GET_SYMPTOMS_LIST_DATA',

  DELETE_POST: 'DELETE_POST',
  DELETE_POST_DATA: 'DELETE_POST_DATA',

  TREATMENT_DATA: 'TREATMENT_DATA',
  TREATMENT_DATA_ALL: 'TREATMENT_DATA_ALL',

  GET_PROFILE_MATCH_LIST: 'GET_PROFILE_MATCH_LIST',
  GET_PROFILE_MATCH_LIST_DATA: 'GET_PROFILE_MATCH_LIST_DATA',

  SAVE_CONDITION: 'SAVE_CONDITION',
  SAVE_CONDITION_DATA: 'SAVE_CONDITION_DATA',

  GET_PRODUCT_REVIEWS: 'GET_PRODUCT_REVIEWS',
  GET_PRODUCT_REVIEWS_DATA: 'GET_PRODUCT_REVIEWS_DATA',

  DEACTIVATE_ACCOUNT: 'DEACTIVATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  NOTIFICATION_TOGGLE: 'NOTIFICATION_TOGGLE',

  GET_TREATMENT_LIST: 'GET_TREATMENT_LIST',
  GET_TREATMENT_LIST_DATA: 'GET_TREATMENT_LIST_DATA',

  DELETE_ACTIVITY: 'DELETE_ACTIVITY',
  DELETE_ACTIVITY_DATA: 'DELETE_ACTIVITY_DATA',

  MY_BOOKMARK: 'MY_BOOKMARK',
  MY_BOOKMARK_DATA: 'MY_BOOKMARK_DATA',

  GET_HOME_SEARCH_LIST: 'GET_HOME_SEARCH_LIST',
  GET_HOME_SEARCH_LIST_DATA: 'GET_HOME_SEARCH_LIST_DATA',

  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_ALL_EVENTS_DATA: 'GET_ALL_EVENTS_DATA',

  GET_EVENT_CATEGORY: 'GET_EVENT_CATEGORY',
  GET_EVENT_CATEGORY_DATA: 'GET_EVENT_CATEGORY_DATA',

  GET_EVENT_LANGUAGE: 'GET_EVENT_LANGUAGE',
  GET_EVENT_LANGUAGE_DATA: 'GET_EVENT_LANGUAGE_DATA',

  GET_CATEGORY_EVENTS: 'GET_CATEGORY_EVENTS',
  GET_CATEGORY_EVENTS_DATA: 'GET_CATEGORY_EVENTS_DATA',

  GET_EVENTS_BY_ID: 'GET_EVENTS_BY_ID',
  GET_EVENTS_BY_ID_DATA: 'GET_EVENTS_BY_ID_DATA',

  GET_FINACIAL_RESOURCE: 'GET_FINACIAL_RESOURCE',
  GET_FINACIAL_RESOURCE_DATA: 'GET_FINACIAL_RESOURCE_DATA',

  GET_FINACIAL_RESOURCE_BY_ID: 'GET_FINACIAL_RESOURCE_BY_ID',
  GET_FINACIAL_RESOURCE_BY_ID_DATA: 'GET_FINACIAL_RESOURCE_BY_ID_DATA',

  REGISTER_EVENT: 'REGISTER_EVENT',
  REGISTER_EVENT_DATA: 'REGISTER_EVENT_DATA',

  COACH_CHAT: 'COACH_CHAT',
  COACH_CHAT_DATA: 'COACH_CHAT_DATA',

  NEWS_LIST: 'NEWS_LIST',
  NEWS_LIST_DATA: 'NEWS_LIST_DATA',

  NEWS_DETAIL: 'NEWS_DETAIL',
  NEWS_DETAIL_DATA: 'NEWS_DETAIL_DATA',

  NEWS_SEARCH: 'NEWS_SEARCH',
  NEWS_SEARCH_DATA: 'NEWS_SEARCH_DATA',

  SUBSCRIPTION_PLAN: 'SUBSCRIPTION_PLAN',
  SUBSCRIPTION_PLAN_DATA: 'SUBSCRIPTION_PLAN_DATA',

  RPM_GET_PERMISSION: 'RPM_GET_PERMISSION',
  RPM_GET_PERMISSION_DATA: 'RPM_GET_PERMISSION_DATA',

  RPM_POST_PERMISSION: 'RPM_POST_PERMISSION',
  RPM_POST_PERMISSION_DATA: 'RPM_POST_PERMISSION_DATA',

  CREATE_SOS: 'CREATE_SOS',
  CREATE_SOS_DATA: 'CREATE_SOS_DATA',

  DELTE_SOS: 'DELTE_SOS',
  DELTE_SOS_DATA: 'DELTE_SOS_DATA',

  FETCH_SOS: 'FETCH_SOS',
  FETCH_SOS_DATA: 'FETCH_SOS_DATA',

  FETCH_RPM: 'FETCH_RPM',
  FETCH_RPM_DATA: 'FETCH_RPM_DATA',

  POST_RPM: 'POST_RPM',
  POST_RPM_DATA: 'POST_RPM_DATA',

  FETCH_PATIENT: 'FETCH_PATIENT',
  FETCH_PATIENT_DATA: 'FETCH_PATIENT_DATA',

  POST_PATIENT: 'POST_PATIENT',
  POST_PATIENT_DATA: 'POST_PATIENT_DATA',

  PATIENT_REFERAL: 'PATIENT_REFERAL',
  PATIENT_REFERAL_DATA: 'PATIENT_REFERAL_DATA',

  INVITED_PATIENT: 'INVITED_PATIENT',
  INVITED_PATIENT_DATA: 'INVITED_PATIENT_DATA',

  DELETE_PATIENT: 'DELETE_PATIENT',
  DELETE_PATIENT_DATA: 'DELETE_PATIENT_DATA',

  FETCH_APPOINTMENT: 'FETCH_APPOINTMENT',
  FETCH_APPOINTMENT_DATA: 'FETCH_APPOINTMENT_DATA',

  SAVE_DOCTORS: 'SAVE_DOCTORS',
  SAVE_DOCTORS_DATA: 'SAVE_DOCTORS_DATA',

  FETCH_DOCTORS: 'FETCH_DOCTORS',
  FETCH_DOCTORS_DATA: 'FETCH_DOCTORS_DATA',

  FETCH_DOCTORS_SEARCH: 'FETCH_DOCTORS_SEARCH',
  FETCH_DOCTORS_SEARCH_DATA: 'FETCH_DOCTORS_SEARCH_DATA',

  DOCTOR_CATEGORY: 'DOCTOR_CATEGORY',
  DOCTOR_CATEGORY_DATA: 'DOCTOR_CATEGORY_DATA',

  DOCTOR_SCHEDULE: 'DOCTOR_SCHEDULE',
  DOCTOR_SCHEDULE_DATA: 'DOCTOR_SCHEDULE_DATA',

  DOCTOR_DETAIL: 'DOCTOR_DETAIL',
  DOCTOR_DETAIL_DATA: 'DOCTOR_DETAIL_DATA',

  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  BOOK_APPOINTMENT_DATA: 'BOOK_APPOINTMENT_DATA',

  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
  CANCEL_APPOINTMENT_DATA: 'CANCEL_APPOINTMENT_DATA',

  RESCHEDULE_APPOINTMENT: 'RESCHEDULE_APPOINTMENT',
  RESCHEDULE_APPOINTMENT_DATA: 'RESCHEDULE_APPOINTMENT_DATA',

  DOCTOR_REVIEW: 'DOCTOR_REVIEW',
  DOCTOR_REVIEW_DATA: 'DOCTOR_REVIEW_DATA',

  WRITE_REVIEW: 'WRITE_REVIEW',
  WRITE_REVIEW_DATA: 'WRITE_REVIEW_DATA',

  BLOCK_USER: 'BLOCK_USER',
  BLOCK_USER_DATA: 'BLOCK_USER_DATA',

  REPORT_OPTIONS: 'REPORT_OPTIONS',
  REPORT_OPTIONS_DATA: 'REPORT_OPTIONS_DATA',

  CANCEL_OPTIONS: 'CANCEL_OPTIONS',
  CANCEL_OPTIONS_DATA: 'CANCEL_OPTIONS_DATA',

  POST_SEARCH: 'POST_SEARCH',
  POST_SEARCH_DATA: 'POST_SEARCH_DATA',

  GET_ONBOARD: 'GET_ONBOARD',
  GET_ONBOARD_DATA: 'GET_ONBOARD_DATA',

  GET_NEWS_BOOKMARK: 'GET_NEWS_BOOKMARK',
  GET_NEWS_BOOKMARK_UPDATE: 'GET_NEWS_BOOKMARK_UPDATE',
  GET_NEWS_BOOKMARK_DATA: 'GET_NEWS_BOOKMARK_DATA',

  GET_POST_COMMENT: 'GET_POST_COMMENT',
  GET_POST_COMMENT_DATA: 'GET_POST_COMMENT_DATA',

  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_NOTIFICATION_READ: 'GET_NOTIFICATION_READ',
  GET_NOTIFICATION_DATA: 'GET_NOTIFICATION_DATA',

  LIKE_WELLNESS: 'LIKE_WELLNESS',
  LIKE_WELLNESS_DATA: 'LIKE_WELLNESS_DATA',
};

export default actionTypes;
